name: Deploy Vite build to GitHub Pages
on:
  push:
    branches:
      - typescript

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Build Vite
        run: npm run build

      - name: Upload built bundle to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
